spring:
  application:
    name: fire-captain-gateway
  
  profiles:
    active: dev
  
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
    
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        # Emergency Report Service
        - id: emergency-report-service
          uri: lb://fire-captain-emergency-report
          predicates:
            - Path=/api/emergency-reports/**
          filters:
            - name: CircuitBreaker
              args:
                name: emergency-report-circuit-breaker
                fallbackUri: forward:/fallback/emergency-report
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY,INTERNAL_SERVER_ERROR
                methods: GET,POST,PUT,DELETE
        
        # Dispatch Service
        - id: dispatch-service
          uri: lb://fire-captain-dispatch
          predicates:
            - Path=/api/dispatches/**
          filters:
            - name: CircuitBreaker
              args:
                name: dispatch-circuit-breaker
                fallbackUri: forward:/fallback/dispatch
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
        
        # Scene Support Service
        - id: scene-support-service
          uri: lb://fire-captain-scene-support
          predicates:
            - Path=/api/scene-supports/**
          filters:
            - name: CircuitBreaker
              args:
                name: scene-support-circuit-breaker
                fallbackUri: forward:/fallback/scene-support
        
        # Completion Report Service
        - id: completion-report-service
          uri: lb://fire-captain-completion-report
          predicates:
            - Path=/api/completion-reports/**
          filters:
            - name: CircuitBreaker
              args:
                name: completion-report-circuit-breaker
                fallbackUri: forward:/fallback/completion-report
        
        # Data Analysis Service
        - id: data-analysis-service
          uri: lb://fire-captain-data-analysis
          predicates:
            - Path=/api/data-analyses/**
          filters:
            - name: CircuitBreaker
              args:
                name: data-analysis-circuit-breaker
                fallbackUri: forward:/fallback/data-analysis
        
        # Monitoring Service
        - id: monitoring-service
          uri: lb://fire-captain-monitoring
          predicates:
            - Path=/api/monitoring/**
          filters:
            - name: CircuitBreaker
              args:
                name: monitoring-circuit-breaker
                fallbackUri: forward:/fallback/monitoring
  
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 1000ms
  
  security:
    jwt:
      secret: fire_captain_gateway_jwt_secret_key_2024
      expiration: 86400000

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml
    min-response-size: 512

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: fire-captain-gateway
      service: gateway

logging:
  level:
    com.firecaptain: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      emergency-report-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
      dispatch-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
      scene-support-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
      completion-report-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
      data-analysis-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
      monitoring-circuit-breaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50

# Custom settings
fire-captain:
  gateway:
    cors:
      allowed-origins: "http://localhost:4200,http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true
    rate-limiting:
      enabled: true
      default-rate: 100
      burst-capacity: 200
