spring:
  application:
    name: fire-captain-dispatch
  
  profiles:
    active: dev
  
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  
  datasource:
    url: jdbc:postgresql://localhost:5432/fire_captain_dispatch
    username: fire_captain_user
    password: fire_captain_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 30000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        jcache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: classpath:ehcache.xml
  
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        default-requeue-rejected: false
  
  security:
    jwt:
      secret: fire_captain_dispatch_jwt_secret_key_2024
      expiration: 86400000

server:
  port: 8082
  compression:
    enabled: true
    mime-types: application/json,application/xml
    min-response-size: 512

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: fire-captain-dispatch
      service: dispatch

logging:
  level:
    com.firecaptain: INFO
    org.springframework.amqp: DEBUG
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Custom settings
fire-captain:
  dispatch:
    queue:
      name: dispatch.created
      exchange: dispatch.events
      routing-key: dispatch.created
    cache:
      ttl: 300
      max-size: 1000
    async:
      enabled: true
      pool-size: 8
