spring:
  application:
    name: fire-captain-config
  
  profiles:
    active: dev
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fire-captain/config-repo
          default-label: main
          search-paths: '{application}'
          clone-on-start: true
          timeout: 10
        native:
          search-locations: classpath:/config

server:
  port: 8888
  compression:
    enabled: true
    mime-types: application/json,application/xml
    min-response-size: 512

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: fire-captain-config
      service: config

logging:
  level:
    com.firecaptain: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Custom settings
fire-captain:
  config:
    encryption:
      enabled: true
      key: fire_captain_config_encryption_key_2024
